
name: money_tracker2
description: A new Flutter project.

publish_to: 'none' # Si este proyecto no se va a publicar, mantenerlo como 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Para íconos de estilo iOS
  google_fonts: ^4.0.3      # Para utilizar fuentes de Google
  font_awesome_flutter: ^10.2.1  # Para usar FontAwesome
  provider: ^6.0.5  # Para manejar el estado con ChangeNotifier

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Linting para mejores prácticas de Flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/  # Asegúrate de que esta carpeta exista si estás utilizando iconos personalizados


